[book]
authors = ["SoloKeys"]
language = "en"
multilingual = false
src = "src"
title = "Solo Bee"

[output.html]
git-repository-url = "https://github.com/nickray/solo-bee"
git-repository-icon = "fa-github"
