[package]
name = "piv-card"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-semihosting = { version = "0.3.5", optional = true}
heapless-bytes = { git = "https://github.com/ycrypto/heapless-bytes", branch = "main" }
interchange = { path = "../interchange" }
serde = { version = "1.0", default-features = false }
trussed = { path = "../crypto-service", package = "crypto-service" }
usbd-ccid = { path = "../usbd-ccid" }

[features]
default = ["cortex-m-semihosting"]
